### PR TITLE
Added target/ to gitignore

### PR DESCRIPTION
**Pull request by deralex**
As in the title, I added Cargo.lock and target/ to the .gitignore file.

Signed-off-by: Alexander Kluth <deralex@cpan.org>

### CODE REVIEW

**Comment by categulario** [comment]
I think Cargo.lock is meant to be kept as part of the repository

**Comment by categulario** [comment]
Indeed:
https://doc.rust-lang.org/cargo/faq.html#why-do-binaries-have-cargolock-in-version-control-but-not-libraries
This is a binary application. It must include Cargo.lock as part of the code.

**Comment by deralex** [comment]
You're right, I wasn't afraid of this.
Changed .gitignore

**Comment by mattdark** [comment]
Hi @deralex and @categulario 

Thanks for your comments. I will merge your pull requests later today. I've been making some changes to the code this week. Sorry for the delay reviewing this.

**Pull request merged**
